### ISSUE TITLE
FEAT: Move Taxiway Splitting to seperate algorithm

### ISSUE THREAD

**Issue by BrakingChanges** [BrakingChanges/widen-line-qgis-plugin#1]
Currently, the taxiway splits are handled by OSM fetching algorithm. I would like more flexibility to move it to a different algorithm so that users can split the taxiways at any time after the OSM fetching. The new algorithm would also be ideally be chained to the taxiway-widening algorithm and would use the select feature -> create new layer from feature method rather than the native QGis "Save vector features" algorithm

**Comment by BrakingChanges** [comment]
@RoboFun01 any thoughts on this?

**Comment by RoboFun01** [comment]
This will be very nice, although I think it would be amazing if the current OSM fetching algorithm is kept at is, and that a new algorithm is created. But it seems great!!
